-- MySQL Script generated by MySQL Workbench
-- Thu Jul 10 19:30:45 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema actividad-1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema actividad-1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `actividad-1` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
-- -----------------------------------------------------
-- Schema actividad-2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema actividad-2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `actividad-2` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `actividad-1` ;

-- -----------------------------------------------------
-- Table `actividad-1`.`country`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad-1`.`country` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `capital` VARCHAR(45) NULL,
  `language` VARCHAR(45) NULL,
  `surface` FLOAT NULL,
  `population` INT(15) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;

USE `actividad-2` ;

-- -----------------------------------------------------
-- Table `actividad-2`.`City`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actividad-2`.`City` (
  `country_id` INT NOT NULL,
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `population` VARCHAR(45) NOT NULL,
  `surface` VARCHAR(45) NOT NULL,
  `ZIPcode` VARCHAR(45) NOT NULL,
  `coast` BOOLEAN NOT NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  INDEX `fk_City_country_idx` (`country_id` ASC) VISIBLE,
  CONSTRAINT `fk_City_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `actividad-1`.`country` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
